[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Backslash"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
live_config_reload = true

[[mouse.bindings]]
action = "Copy"
mouse = "Left"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

[[colors.indexed_colors]]
color = "0xf99157"
index = 16

[[colors.indexed_colors]]
color = "0xa3685a"
index = 17

[[colors.indexed_colors]]
color = "0x393939"
index = 18

[[colors.indexed_colors]]
color = "0x515151"
index = 19

[[colors.indexed_colors]]
color = "0xb4b7b4"
index = 20

[[colors.indexed_colors]]
color = "0xe0e0e0"
index = 21

[colors.bright]
black = "0x999999"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xffffff"
yellow = "0xffcc66"

[colors.cursor]
cursor = "0xcccccc"
text = "0x2d2d2d"

[colors.normal]
black = "0x2d2d2d"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xcccccc"
yellow = "0xffcc66"

[colors.primary]
background = "0x2d2d2d"
foreground = "0xcccccc"

[cursor]
blink_interval = 750
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.bold_italic]
family = "Inconsolata"
style = "Bold"

[font.italic]
family = "Inconsolata"
style = "Regular"

[font.normal]
family = "Inconsolata"
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 1.0

[window.padding]
x = 4
y = 4

[keyboard]
